export type RecoveryContext =
  | "wallet-connect"
  | "wallet-signature"
  | "wallet-history"
  | "wallet-execution"
  | "wallet-status"
  | "testnet-status";

export type RecoveryTone = "warning" | "danger" | "info";

export type RecoveryNotice = {
  context: RecoveryContext;
  message: string;
  steps: string[];
  title: string;
  tone: RecoveryTone;
};

export function getErrorMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  if (typeof error === "string") return error;
  return "Unexpected wallet error.";
}

function matches(message: string, patterns: RegExp[]) {
  return patterns.some((pattern) => pattern.test(message));
}

export function createRecoveryNotice(error: unknown, context: RecoveryContext): RecoveryNotice {
  const message = getErrorMessage(error);
  const normalized = message.toLowerCase();

  if (matches(normalized, [/reject/, /denied/, /declin/, /cancel/, /user refused/])) {
    return {
      context,
      message,
      steps: [
        "Review the wallet popup and approve only if the program, inputs, network, and fee match this page.",
        "Retry the same step after the wallet is unlocked and focused."
      ],
      title: context === "wallet-signature" ? "Signature rejected" : "Wallet request rejected",
      tone: "warning"
    };
  }

  if (matches(normalized, [/insufficient/, /balance/, /fee/, /credit/, /fund/])) {
    return {
      context,
      message,
      steps: [
        "Fund the connected Aleo testnet wallet with public credits.",
        "Retry after the wallet shows enough balance for the public execution fee."
      ],
      title: "Insufficient testnet balance",
      tone: "danger"
    };
  }

  if (matches(normalized, [/not installed/, /not detected/, /unsupported/, /not available/, /extension/])) {
    return {
      context,
      message,
      steps: [
        "Install or enable Leo, Shield, Puzzle, or Fox Wallet in this browser.",
        "Refresh the page after the extension injects its wallet adapter."
      ],
      title: "Wallet extension unavailable",
      tone: "warning"
    };
  }

  if (matches(normalized, [/not connected/, /disconnect/, /connect an aleo wallet/])) {
    return {
      context,
      message,
      steps: [
        "Reconnect the Aleo wallet from the header.",
        "Retry after the connected address is visible."
      ],
      title: "Wallet disconnected",
      tone: "warning"
    };
  }

  if (matches(normalized, [/broadcast/, /network/, /timeout/, /failed to fetch/, /testnet api/, /api request/, /unavailable/])) {
    return {
      context,
      message,
      steps: [
        "Keep the wallet execution id or transaction id visible before retrying.",
        "Retry after the testnet API or wallet network connection is available."
      ],
      title: context === "testnet-status" ? "Testnet status unavailable" : "Network or broadcast unavailable",
      tone: "info"
    };
  }

  if (matches(normalized, [/verify/, /signature did not/, /invalid signature/])) {
    return {
      context,
      message,
      steps: [
        "Reconnect the expected Aleo address.",
        "Sign a fresh ownership challenge generated by this page."
      ],
      title: "Signature verification failed",
      tone: "danger"
    };
  }

  if (context === "wallet-execution") {
    return {
      context,
      message,
      steps: [
        "Check the wallet popup for the exact execution error.",
        "Retry with the same ticket after confirming network, inputs, and fee."
      ],
      title: "Execution recovery needed",
      tone: "danger"
    };
  }

  return {
    context,
    message,
    steps: [
      "Retry the step after confirming the wallet is unlocked and connected.",
      "Refresh the page if the wallet adapter state looks stale."
    ],
    title: "Recovery needed",
    tone: "warning"
  };
}
